namespace CryBar.TMM;

public sealed class TmmAutoAttachInfo
{
    public bool AutoAttachCorpseToBone { get; init; }
    public string CorpseAttachBoneName { get; init; } = "";
    public string DefaultDeathAnimation { get; init; } = "";
    public bool UsesAutoGeneratedImpactPoints { get; init; }
    public string DefaultIdleAnimationPath { get; init; } = "";
    public float[][]? ManualImpactPoints { get; init; }
}
